quil-lang/magicl

- Makefile
I don't have an Ubuntu box to check that line for Debian dependencies is still ok, but given that the Makefile is able to be parsed, I assume this is ok.
> Added dependency installation for RedHat based platforms.

- einsum.lisp
This is macro for working with summations over multidimensional arrays, similar to numpy's einsum. As an example, the code below computes a matrix-vector product, storing the results in a fresh array (it's also possible to do this in place, if something other than `_` had been given).
```
CL-USER> (macroexpand-1 '(einsum (_ i) (foo i j) (bar j)))
(PROGN
(UNLESS (= 2 (ARRAY-RANK FOO))
(ERROR
"Incompatible dimensions: given array ~A with dimensions ~A and indices ~A"
FOO (ARRAY-DIMENSIONS FOO) '(I J)))
(UNLESS (= 1 (ARRAY-RANK BAR))
(ERROR
"Incompatible dimensions: given array ~A with dimensions ~A and indices ~A"
BAR (ARRAY-DIMENSIONS BAR) '(J)))
(UNLESS (= (ARRAY-DIMENSION FOO 0))
(ERROR "Index variable ~A applied to arrays with incompatible dimensions"
'I))
(UNLESS (= (ARRAY-DIMENSION …
```
> Add EINSUM

- src/high-level/high-level.lisp
Code did assume, that array-element-type will return one particular
form of the data type. There is no guarantee in the spec, that this
will be the case, so instead of calling equal on results we compare
them by means of subtypep (and etypecase).
> high-level: do not make assumption about array-element-type result

- README.md
The docker subdirectory was removed in the following commit, but the README still mentions running `make -C docker`.
https://github.com/rigetti/magicl/commit/9228099ab7cc079c2c737cff43a78c1260e0f356
> Remove references to docker build

- src/high-level/high-level.lisp
- src/high-level/random.lisp
- src/packages.lisp
This changes the behavior of RANDOM-GAUSSIAN-MATRIX. The previous implementation did not create a random gaussian matrix: for example, the distribution did not have a rotational symmetry (since the entries are all nonnegative). As a side note, the existence of min/max optional arguments to ALEXANDRIA:GAUSSIAN-RANDOM is bad design on their part since they look like mean/variance in code.
This change impacts other random matrices, e.g. the random unitaries which are also not quite random (since the QR factorization inherits the first unit column up to scale in the Q matrix from the first column of the gaussian matrix). As a result, this change breaks one of the state prep tests in quilc, but I have an easy fix lined up.
Since we're here, I'm also hoping to export a few more things from the …
> Change behavior of RANDOM-GAUSSIAN-MATRIX

- src/high-level/high-level.lisp
As promised in #54, here is a patch that makes `multiply-complex-matrix` two orders of magnitude faster and less memory-hungry (see results below).
```lisp
(in-package #:magicl)
(defparameter *n* 2048)
(defparameter *matrix* (magicl:random-unitary *n*))
(defparameter *vector* (magicl:random-matrix *n* 1))
(progn
(sb-ext:gc :full t)
(dotimes (i 3)
(time (multiply-complex-matrices *matrix* *vector*))))
(format t "===================================~%")
(progn
(sb-ext:gc :full t)
(dotimes (i 3)
(time (multiply-complex-matrices-old *matrix* *vector*))))
;;; WITH THIS PATCH.
;; Evaluation took:
;;   0.005 seconds of real time
;;   0.017629 seconds of total run time (0.017518 user, 0.000111 system)
;;   360.00% CPU
;;   12,243,972 processor cycles
;;   1,840 bytes consed
;;   
;; Evaluation …
```
> Simplify MULTIPLY-COMPLEX-MATRIX. Cons less, compute more.

- src/high-level/high-level.lisp
- src/packages.lisp
LAPACK provides a separate function specifically intended for diagonalizing Hermitian matrices, which has turned out to be useful in quilc. This PR adds `hermitian-eig`, a mimic to `eig`, which wraps this function. I've put no thought into the interface; I'd be happy to hear someone else's thoughts on that.
> add a wrapper for `ZHEEV`

- src/high-level/high-level.lisp
- tests/high-level-tests.lisp
This implements the CS decomposition in the base case of an equipartitioned 2x2 unitary matrix.
The function `csd-2x2-basic` is significantly faster and less memory-hungry than the call to `lapack-csd` as shown below:
```lisp
MAGICL> (let ((p 1)
(q 1)
(u (magicl:random-unitary 2)))
(sb-ext:gc :full t)
(time
(dotimes (i 100000)
(when (= p q 1)
(csd-2x2-basic u p q))))
(sb-ext:gc :full t)
(time
(dotimes (i 100000)
(lapack-csd u p q))))
Evaluation took:
0.144 seconds of real time
0.143749 seconds of total run time (0.130993 user, 0.012756 system)
[ Run times consist of 0.003 seconds GC time, and 0.141 seconds non-GC time. ]
100.00% CPU
390,120,550 processor cycles
103,980,336 bytes consed
Evaluation took:
0.507 seconds of real time
0.506777 seconds of total run time (0.488778 user, 0.017999 …
```
> Faster CS decomposition for equipartitioned 2x2 unitary matrices.

- examples.lisp
- magicl-examples.asd
- src/packages.lisp
The `expm` symbol exists in the `magicl-transcendental` package instead.
> Do not export expm symbol from magicl package

- magicl-gen.asd
Requirement was added for magicl in
a37039a8537dabb0095306b8e463c7aca9b4c5c9, needs to be reflected in
magicl-gen as well, since they share src/packages.lisp
> Add abstract-classes to magicl-gen

- src/high-level/vector.lisp
Without this, `(let ((v (ones '(10)))) (slice v '(0) '(3)))` won't work.
> Implement LAYOUT method for vectors so that we can SLICE them

- examples.lisp
- src/high-level/util.lisp
The default threshold is to strict and causes tests to fail occasionally
Resolves #85
> Loosen float comparison thresholds

- src/high-level/lapack-bindings.lisp
- src/high-level/lapack-generics.lisp
- src/high-level/lapack-templates.lisp
- src/high-level/matrix.lisp
- src/high-level/vector.lisp
- tests/matrix-tests.lisp
Adds lapack-based matrix-vector multiplication for supported types and overhauls lapack high-level binding generation. These bindings support all the same options that a normal matrix-matrix `mult` does including scaling, transposing, and accounting for layout of supplied matrix.
The main issue I have with reusing `mult` here is that there is an unused parameter of `transb`.
See #82
> Add matrix-vector multiplication

- tests/matrix-tests.lisp
`magic-...` -> `magicl-...`
Side note: The test runners are not updating the status on github
> Fix typo in test-identity-matrix-p

- src/high-level/constructors.lisp
This is a band-aid fix for #86 to optimize from-list to be O(n).
Once a central tensor registry is implemented (#95) a second path to coerce the input sequence to the correct array type (as described in #86).
> Optimize from-list

- magicl-tests.asd
- src/high-level/constructors.lisp
- src/high-level/lapack-templates.lisp
- src/high-level/types/complex-double-float.lisp
- tests/constructor-tests.lisp
- transcendental/transcendental.lisp
Allows for multi-dimensional arrays as input to `FROM-ARRAY` (Resolves #102)
This also adds a new kw arg to `FROM-ARRAY`, `INPUT-LAYOUT` which allows for reindexing of input arrays (`INPUT-LAYOUT` does not need to be the same as `LAYOUT`). 
As a bonus, fixes a bug that came up while testing this PR caused by `LAPACK-INV` not setting the layout of the tensor to `COLUMN-MAJOR` after fortran touched it.
> Allow for multi-dimensional arrays in FROM-ARRAY constructor.

- examples.lisp
- src/high-level/lapack-templates.lisp
- src/high-level/matrix.lisp
- tests/high-level-tests.lisp
This allows for non-square matrices in these routines, e.g.
```
MAGICL> (qr (rand '(4 2)))
#<MATRIX/DOUBLE-FLOAT (4x2):
0.551     0.151
0.137     0.808
0.659     0.122
0.493    -0.556>
#<MATRIX/DOUBLE-FLOAT (2x2):
1.310     1.189
0.000     0.857>
```
This also addresses #78. The previous `order` business was a bit too confusing imo. The key thing that's needed for working with LAPACK is to extract upper/lower square submatrices. If we had slices, I would have used those, but for now I've just added a `:square` flag. This follows the LAPACK convention: when enabled, `upper-triangular` takes the upper rightmost square submatrix, and `lower-triangular` takes the lower leftmost, e.g.
```
MAGICL> (from-list '(1 2 3 4 5 6) '(2 3))
#<MATRIX/INT32 (2x3):
1      2      3
4      5      6>
MAGICL> …
```
> Allow for rectangular matrices in QR, QL, RQ, LQ factorizations.

- magicl-transcendental.asd
A fresh `(ql:quickload :magicl-tests)` failed for me today when trying to compile `magicl/transcendental/expokit.f` with gfortran 10.2.0. Peeking at the error, I see
```
...
294 |          call DNCHBV(mx,sgn*t_step,wsp(ih),mh,wsp(iexph),wsp(ifree+mx))
|                                                                        1
Error: Type mismatch in argument 'wsp' at (1); passed REAL(8) to COMPLEX(8)
/Users/erik/.quicklisp/dists/quicklisp/software/magicl-v0.7.0/transcendental/expokit.f:1901:72:
1901 |          call DNCHBV(mx,sgn*t_step,wsp(ih),mh,wsp(iexph),wsp(ifree+mx))
|                                                                        1
Error: Type mismatch in argument 'wsp' at (1); passed REAL(8) to COMPLEX(8)
/Users/erik/.quicklisp/dists/quicklisp/software/magicl-v0.7.0/transcend …
```
> Ask gfortran 10 to take it easy

- src/high-level/matrix.lisp
- src/high-level/types/complex-double-float.lisp
- tests/high-level-tests.lisp
This fixes a bug where `LAPACK-CSD` gives the wrong values for row-major matrices.
In previous versions of magicl, matrices constructed with `FROM-ARRAY` had their layout determined by the layout of the input array, and so essentially all matrices had `:column-major` by default. More recent changes f761ef92410e155886b70649abf1c29b8cb6ddd7 allow this to be controlled by a keyword argument of `FROM-ARRAY`, and the default was changed to `:row-major`. Unfortunately `LAPACK-CSD` did not handle this correctly for two reasons:
- `:column-major` input layout was hardcoded by default in `LAPACK-CSD`
- The actual code responsible for dereferencing pointers for the underlying lapack library, `PTR-REF`, was incomplete.
This issue was not exercised by `magicl-tests`, but does come up in …
> Fix handling of matrix layout in PTR-REF and LAPACK-CSD

- src/backend-function.lisp
This is in response to [this build failure](http://report.quicklisp.org/2021-03-31/failure-report/magicl.html#magicl_ext-blas). I couldn't reproduce this on a 2.1.2 SBCL.
Some old SBCLs are erroring, probably\* because some compile-time-needed definitions (`defvar` and `defun`) are needed for a subsequent `deftype` and `defmacro`. SBCL has typically not been picky about this, but maybe it is in this tangle of definitions.
We fix by just adding an `eval-when` around these definitions.
Tests pass locally; not sure about Quicklisp or old SBCL.
\* I didn't actually download an ancient SBCL and test. This was a very likely hunch by `phoe` from `#lisp` on 3/31/21.
> add EVAL-WHEN around compile-time-needed definitions

- magicl.asd
- src/extensions/common/package.lisp
- src/extensions/common/ptr-ref.lisp
- src/extensions/lapack/lapack-csd.lisp
- src/high-level/matrix.lisp
- src/packages.lisp
This eliminates CFFI and CFFI-LIBFFI as dependencies, making
MAGICL easier to load on platforms without a C compiler.
> remove MAGICL/EXT from MAGICL/CORE

- magicl-tests.asd
- magicl.asd
- src/high-level/allocation.lisp
- src/high-level/constructors.lisp
- src/high-level/einsum.lisp
- src/high-level/matrix.lisp
- src/high-level/tensor.lisp
- src/high-level/vector.lisp
- src/packages.lisp
- tests/allocation-tests.lisp
- tests/high-level-tests.lisp
It'd be nice if we had a bit more control over where tensor storage comes from, so this adds that. My main interest is in using this with `static-vectors`, but we could also consider other options (e.g. posix shared memory, as in the QVM).
> Add lisp & static-vectors allocators for tensor storage

- src/extensions/lapack/lapack-bindings.lisp
- src/extensions/lapack/lapack-generics.lisp
- src/extensions/lapack/lapack-templates.lisp
- src/high-level/constructors.lisp
- src/high-level/matrix.lisp
- src/high-level/tensor.lisp
- src/high-level/vector.lisp
- src/packages.lisp
- tests/high-level-tests.lisp
This adds a `linear-solve` routine for Ax=b. Right now it only supports full-rank matrices via LU-factorization, although in  the future we could add more cases. This is faster and safer than multiplying by `(inv A)`.
> Add LINEAR-SOLVE

- magicl.asd
Call ASDF/OUTPUT-TRANSLATIONS:APPLY-OUTPUT-TRANSLATIONS on Fortran
output objects so that they are treated consistently with Lisp
objects, e.g. written into $HOME/.cache/common-lisp/... instead of
inline in the source tree.
(This resolves a problem I have adding Magicl to a Nix-based
environment that stores sources on a read-only filesystem: Magicl
would try to compile the Fortran code there in place and fail.)
Co-authored-by: Luke Gorrie <lukego@gmail.com>
***
This duplicates @lukego's PR #151 but fixes the formatting.
> APPLY-OUTPUT-TRANSLATIONS on Fortran outputs

- src/extensions/expokit/load-libs.lisp
File changed: src/extensions/expokit/load-libs.lisp
This changes fortran library loading to correspond with the recent
changes in magicl.asd that changed the directory location of the
LIBEXPOKIT fortran library.
Previously, the loading code defined the library to exist in a
directory relative to the source tree, and now it defines that
directory relative to the output tree, i.e., where we output fasls,
etc., as per the recent change in magicl.asd.
We now use cffi:*foreign-library-directories* to define the location
instead of sticking read-time-evaluated pathnames into the library
definition. It's less code, since it does not need to branch per
platform (cf. old darwin/linux cases). It also should work on Windows
besides macOS and Linux, though that hasn't been tested. It also is
better …
> Resolves #156: Cannot load fortran lib

- src/extensions/blas/package.lisp
- src/extensions/common/with-array-pointers.lisp
- src/extensions/lapack/lapack-templates.lisp
- src/extensions/lapack/package.lisp
- src/high-level/abstract-tensor.lisp
- src/packages.lisp
These changes should make magicl work with LispWorks 8 when installed through `quicklisp/local-projects`.
> Make magicl compatible with LispWorks 8

- README.md
- doc/requirements.md
ECL and MagiCL were modified in 2019 to work together.
> cosmetic: add ECL to supported implementations

- doc/high-level.md
- src/high-level/abstract-tensor.lisp
- src/packages.lisp
- tests/abstract-tensor-tests.lisp
Extend basic basic operations (i.e. elementwise ops) in three ways:
1. Allowing for a `number` instead of an `abstract-tensor` type as one of the arguments
- This means something like `(.+ A 10)` behaves as it reads - i.e. add 10 to each element of `A`.  An alternative would have been to create a tensor the same type/shape as `A` and set all elements to 10...and then...add to `A`
2. Add an elementwise `.max` and `.min`
- It might just be my use-case, but this means creating a [ReLU](https://en.wikipedia.org/wiki/Rectifier_(neural_networks)) function is then as simple as `(.max 0.0 A)`
3. Add elementwise `.exp` and `.log` (natural log)
- These need a `unary-operator` function, which will look suspiciously like the existing `binary-operator`, but with only one argument
1. There are no …
> Extend basic operations

- Makefile
See [1] for the memory required to compile LAPACK as of May 2022.
[1] https://github.com/quil-lang/magicl/issues/169
> Add explicit command for SBCL heap size

- src/extensions/blas/load-libs.lisp
- src/extensions/lapack/load-libs.lisp
homebrew on macOS on ARM defaults to a different directory than previously on x86
> add homebrew path for shared libraries

- src/high-level/constructors.lisp
- src/high-level/matrix-functions/eig/eig.lisp
- src/high-level/tensor.lisp
- src/high-level/vector.lisp
- src/packages.lisp
Hi,
when I specified type for vector and tensor, error:
MAGICL> (from-list  '(1 2 3 4 5 6) '(6) :type 'double-float)
The value
1
is not of type
DOUBLE-FLOAT
when setting an element of (ARRAY DOUBLE-FLOAT)
[Condition of type TYPE-ERROR]
after fix:
MAGICL> (from-list '(1 2 3 4 5 6) '(6) :type 'double-float)
#<VECTOR/DOUBLE-FLOAT (6):
1.000
2.000
3.000
4.000
5.000
6.000>
best wishes!
> Bug fix, specified type.

- tests/matrix-tests.lisp
07edc0f changed the return type of `magicl:row` and `magicl:column`, causing `test-matrix-stacking` to fail.
This was also mentioned in issue #203.
> fix matrix stacking test

- doc/dev-how-to.md
- src/extensions/blas/arithmetic.lisp
- src/extensions/lapack/lapack-generics.lisp
- src/high-level/matrix-functions/svd.lisp
- src/high-level/util.lisp
- src/packages.lisp
Addresses https://github.com/quil-lang/magicl/issues/209 and related compiler warnings.
> Fix compiler warnings when loading `magicl`
